package com.chatapp.common.protocol;

public enum MessageType {
    // Authentication
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    REGISTER_REQUEST,
    REGISTER_RESPONSE,
    LOGOUT_REQUEST,
    LOGOUT_RESPONSE,
    FORGOT_PASSWORD_REQUEST,
    FORGOT_PASSWORD_RESPONSE,
    VERIFY_OTP_REQUEST,
    VERIFY_OTP_RESPONSE,

    // Friend
    ADD_FRIEND_REQUEST,
    ADD_FRIEND_RESPONSE,
    ACCEPT_FRIEND_REQUEST,
    ACCEPT_FRIEND_RESPONSE,
    BLOCK_FRIEND_REQUEST,
    BLOCK_FRIEND_RESPONSE,
    GET_FRIENDS_REQUEST,
    GET_FRIENDS_RESPONSE,

    // Chat
    SEND_MESSAGE_REQUEST,
    SEND_MESSAGE_RESPONSE,
    RECEIVE_MESSAGE,
    GET_MESSAGES_REQUEST,
    GET_MESSAGES_RESPONSE,
    TYPING_INDICATOR,
    READ_RECEIPT,

    // File
    FILE_OFFER,
    FILE_ACCEPT,
    FILE_REJECT,
    FILE_INFO,

    // Call
    CALL_REQUEST,
    CALL_ACCEPT,
    CALL_REJECT,
    CALL_END,
    CALL_INFO,

    // Status
    STATUS_UPDATE,
    USER_ONLINE,
    USER_OFFLINE,

    // Error
    ERROR
}